select A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
  ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (select MAX(A2.LENGTH) from FISH_INFO A2 where A.FISH_TYPE = A2.FISH_TYPE)
ORDER BY A.ID