WITH TOTAL AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
)
SELECT T.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM TOTAL T
JOIN HR_EMPLOYEES E on T.EMP_NO = E.EMP_NO
WHERE T.SCORE = (SELECT MAX(SCORE) FROM TOTAL);